"""介面規格。W1 末凍結，改動要全員同意。"""

from .pack import KnowledgeRef, PackSpec, Thresholds
from .protocol import ENTRYPOINT_FACTORY, ScamModule
from .schemas import (
    DISCLAIMER,
    HOTLINE,
    ActionItem,
    AnalyzeInput,
    CaseProfile,
    Confidence,
    CoverageStatus,
    HealthCheck,
    HealthReport,
    ImageInput,
    LegalRef,
    MaskedText,
    ModuleHint,
    ModuleInfo,
    Plan,
    Redaction,
    RiskLevel,
    RoutedResponse,
    SimilarCase,
    TraceEvent,
    Verdict,
)

__all__ = [
    "DISCLAIMER",
    "ENTRYPOINT_FACTORY",
    "HOTLINE",
    "ActionItem",
    "AnalyzeInput",
    "CaseProfile",
    "Confidence",
    "CoverageStatus",
    "HealthCheck",
    "HealthReport",
    "ImageInput",
    "KnowledgeRef",
    "LegalRef",
    "MaskedText",
    "ModuleHint",
    "ModuleInfo",
    "PackSpec",
    "Plan",
    "Redaction",
    "RiskLevel",
    "RoutedResponse",
    "ScamModule",
    "SimilarCase",
    "Thresholds",
    "TraceEvent",
    "Verdict",
]
